server:
  port: 8090

spring:
  application:
    name: email-notification-service
  kafka:
    consumer:
      bootstrap-servers: localhost:9092,localhost:9094
#      group-id: user-events
      properties:
        spring:
          json:
            trusted:
              packages: "com.artemyakkonen.core"
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 10000
            logger-level: basic            

resilience4j:
  circuitbreaker:
    instances:
      userServiceCB:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true   

logging:
  level:
    root: info
#    org.springframework.kafka: DEBUG
#    com.artemyakkonen: debug
